# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160303_0929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationmodel',
            unique_together=set([('longitude', 'latitude')]),
        ),
    ]
